# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: ThusithaDJ.Sphinx
PackageVersion: 0.1.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-10-04
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ThusithaDJ/Sphinx/releases/download/sphinx-v0.1.0/Sphinx_0.1.0_x64-setup.exe
    InstallerSha256: 3AB3DABE956CF4C881A5EB28BCA379CDFF2805FE56172E494B564469B16DDBE3
ManifestType: installer
ManifestVersion: 1.6.0
